server:
  port: 9004

spring:
  application:
    name: kuke-board-like-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: root1234!
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none